### ISSUE TITLE
Clean up irrelevant commits in the scrape-util configs folder

### ISSUE THREAD

**Issue by ryantanaka** [erdl/scrape_util_configs#3]
### steps
1. create a copy of the csbcd_config folder for archiving purposes
2. git init the folder that is used in production to reset the log
3. make a new commit for this issue adding the existing files

**Comment by ryantanaka** [comment]
### back up of the csbcd-configs folder with the old git repo 
[csbcd-configs.zip](https://github.com/erdl/scrape_util_configs/files/1917650/csbcd-configs.zip)

**Comment by ryantanaka** [comment]
Ignore all those commits, the only one that will be used is the most recent one. `47bf40e`

**Comment by carlosparadis** [comment]
@ryantanaka headsup, I still don't have any PR or can re-open the ones submitted. You need to send a new one.

**Comment by ryantanaka** [comment]
@carlosparadis, its reopened and ready to go.

**Comment by carlosparadis** [comment]
@ryantanaka I believe this issue is now done. pleased re-open otherwise.

**Comment by carlosparadis** [comment]
@ryantanaka Actually it is missing a note here: Did you address the password concern on the config here?

**Comment by ryantanaka** [comment]
@carlosparadis, yeah it was missing that note. My last comment was before you looked over it and found the password. Password concern is addressed in my commits, atm I'm updating the now incorrect survey_display paths. Will get this one done soon.

**Comment by ryantanaka** [comment]
Notes regarding changes made to update `/var/local/csbcd-configs/scrape-util-projects/survey_display/config.toml`:

1. survey_display writes responses to `/var/www/www-data/occquse/responses`. For consistency, I've changed `occquse` to `survey_display`. As a result, `source = '/var/www/www-data/occquse/responses/'     `  in `scrape-util`'s `config.toml` for `survey_display` will be updated to `source = '/var/www/www-data/survey_display/responses/'`.

2. `scrape-util` writes raw `survey_display` output to `/var/local/scrape-util/projects/occupant-query/raw`. I've changed `occupant-query` to `survey_display`. As a result, I changed `on-raw = '/var/local/scrape-util/projects/occupant-query/raw' ` in `scrape-util`'s `config.toml` for `survey_display` to be `on-raw = '/var/local/scrape-util/projects/survey_display/raw' `

3. `parser = "occupant-query" ` in the `scrape-util survey display config` needs to use `survey_display` for consistency. Currently looking to complete this [issue](https://github.com/erdl/legacy-scrape-util/issues/24) first.

This update to use the name `survey_display` has some cascading side effects so I'm trying to take care of that first.
