### ISSUE TITLE
remove survey_display configs

### ISSUE THREAD

**Issue by ryantanaka** [erdl/scrape_util_configs#8]
`survey_display` now directly inserts survey responses into the database via `flask` and `psycopg2` so `scrape-util` doesn't need to process `survey_display` data
(see https://github.com/erdl/survey_display/issues/43).  `survey_display` configs for `scrape-util` can be removed. 

Also, the original backup of the configs can be found at https://github.com/erdl/scrape_util_configs/issues/3.

**Comment by carlosparadis** [comment]
@ryantanaka can you test on production and let me know if it works so we can close this? :) Sorry I lost track of this one.

**Comment by ryantanaka** [comment]
@carlosparadis  done,
scrape util is still running fine and i checked that we are still getting data. closing this
